# Generated by Django 4.2.4 on 2023-08-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('hero', models.CharField(max_length=20)),
                ('heroine', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('plot', models.TextField(blank=True, max_length=200, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.generes')),
            ],
        ),
    ]
